Collab
MaRDI4NFDI/portal-compose pull request #159
Opened 2022-03-22 14:17 UTC by LizzAlice

# MaRDI Pull Request

**Changes**:
- set up mongodb container necessary for collab
- set up collab
- depends on new docker-wikibase image with pull request https://github.com/MaRDI4NFDI/docker-wikibase/pull/15

**Instructions for PR review**:
- [x] Conceptual Review (Logic etc...) 
- [x] Code Review (Review your implementation) 
- [x] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

2022-03-22 14:30 UTC, Hyper-Node requested changes
please answer question.

2022-03-22 14:30 UTC, Hyper-Node commented on docker-compose.yml
> +  #  ports:
remove comment here

2022-05-04 13:39 UTC, physikerwelt approved these changes
I think one approval is enough to merge the change

2022-05-04 13:42 UTC, physikerwelt commented on mediawiki/LocalSettings.d/LocalSettings.override.php
> +$wgVisualEditorRebaserURL = 'http://localhost:8081';
@LizzAlice will this work? I guess in production this might need to point to another URL?

2022-05-23 09:17 UTC, merged

2022-05-27 08:46 UTC, dajuno commented on prometheus/traefik-pass
> +change-this-password
Adding this file is a mistake, right? It is not used anymore since 3659e1a1d98280f7f15fa22787e8ff170150f856 (and was never version controlled)