Tentative fix for visual editor
MaRDI4NFDI/portal-compose pull request #75
Opened 2022-01-26 10:46 UTC by Hyper-Node

For enabling visual editor on private pages

# MaRDI Pull Request
(this template is to be filled out by the person who is creating the pull-request)

**Goal**: 
(bigger goal you want to achieve with this PR)
- Quick fix enabling visual editor 
- havent tested yet, docs says it should work that way

**Instructions for PR review**:
(these are marked by the person creating the PR and should be checked by the reviewer) 
- [ ] Conceptual Review (Logic etc...) 
- [ ] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 
- Consideration to move that to visualeditor.php

**Checklist for this PR**: 
- [ ] At least one reviewer has been assigned. 
- [ ] All related issues with further descriptions are linked.

**Note for linking-issue across repositories**:
If the issue is not in the same Repository as the PR. The issue can be referenced with by 
typing the following here in this markdown: 
user/repository#number
i.e: MARDI4NFDI/example_repo#1

2022-01-26 14:18 UTC, physikerwelt commented
Just a side comment. I am not a big fan of this mardi pull request template. It makes it hard to find the actual information that are different from other pull request. For example in email updates one has little chances to monitor what this is about without  reading everything in detail. Maybe we can agree to remove boilerplate text before merging. The check boxes are ok though, but should be reduced to one word with link to detailed explaination. For example

> - [x] At least one reviewer has been assigned.

 ->

- [x] [reviewer assigned](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review): aot29

As a bonus one could add the name of the reviewer bit that is not required

> - [x] All related issues with further descriptions are linked.

->

- [x] [issues linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

2022-01-26 14:40 UTC, physikerwelt requested changes

2022-01-26 14:40 UTC, physikerwelt commented on mediawiki/LocalSettings.d/LocalSettings.override.php
> +    'Private' => true,
move after line 112.

2022-01-26 16:31 UTC, Hyper-Node commented
> Just a side comment. I am not a big fan of this mardi pull request template. It makes it hard to find the actual information that are different from other pull request. For example in email updates one has little chances to monitor what this is about without reading everything in detail. Maybe we can agree to remove boilerplate text before merging. The check boxes are ok though, but should be reduced to one word with link to detailed explaination. For example
> 
> > * [x]  At least one reviewer has been assigned.
> 
> ->
> 
>     * [x]  [reviewer assigned](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review): aot29
> 
> 
> As a bonus one could add the name of the reviewer bit that is not required
> 
> > * [x]  All related issues with further descriptions are linked.
> 
> ->
> 
>     * [x]  [issues linked](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

simplified it.

2022-01-27 09:46 UTC, aot29 approved these changes
Probably works, but on my local machine I get a timeout.

2022-01-27 09:56 UTC, physikerwelt approved these changes

2022-01-27 09:56 UTC, merged